### ISSUE TITLE
fatal error: Double value cannot be converted to Int because it is either infinite or NaN

### ISSUE THREAD

**Issue by k1nk4** [tschob/AudioPlayerManager#11]
I'm getting this error when i run the code

        player.setup()
        
        player.play(url: URL(string: "url/media/podcast/z3f1fi18.mp3"))

Error at class: AudioTrack
method: updateNowPlayingInfoPlaybackDuration

open func updateNowPlayingInfoPlaybackDuration() {
		if let _playerItem = self.playerItem {
			let duration = NSNumber(value: Int(CMTimeGetSeconds(_playerItem.asset.duration)) as Int)
			self.nowPlayingInfo?[MPMediaItemPropertyPlaybackDuration] = duration

any solution?

**Comment by k1nk4** [comment]
> aluguetemporada

**Comment by tschob** [comment]
@k1nk4 Which AudioPlayerManager version are you using? I can't reproduce it so far. Can you provided me the complete URL of the failing track?

**Comment by k1nk4** [comment]
Using AudioPlayerManager (1.2.0)

url: http://aluguetemporada.deway.com.br/media/podcast/z3f1fi18.mp3

**Comment by tschob** [comment]
@k1nk4 Sorry for the late answer. I was able to reproduce the crash and provided a fix for Swift 2.3 and 3.0
