### ISSUE TITLE
How do I get the current playback time?

### ISSUE THREAD

**Issue by PrasenjitGiri** [tschob/AudioPlayerManager#14]
How do I get the current playback time from this library? I need to update the screen. 

For eg: addPeriodicTimeObserver

**Comment by tschob** [comment]
Hi. You have to add a callback block. There is a callback for track state changes (play, pause, next track,...) and one for the playback time. The playback callback is called each 0.1 seconds.

Taken from the Example project (is contained in this repo):
```
// Listen to the playback time changed. This event occurs every `AudioPlayerManager.PlayingTimeRefreshRate` seconds.
AudioPlayerManager.shared.addPlaybackTimeChangeCallback(self, callback: { [weak self] (track: AudioTrack?) in
    self?.updatePlaybackTime(track)
})

func updatePlaybackTime(_ track: AudioTrack?) {
    self.positionLabel?.text = "\(track?.displayablePlaybackTimeString() ?? "-")/\(track?.displayableDurationString() ?? "-")"
}
```

**Comment by PrasenjitGiri** [comment]
Thank you.
