### ISSUE TITLE
any headers needed from the server

### ISSUE THREAD

**Issue by muhammad-naderi** [tschob/AudioPlayerManager#18]
the library works great with other mp3 links, however it does not play my link (from my server) 
perhaps it is something that i need to do in my server, however if you can help me, it would be a lot appreciated 

my link 
http://projectm.e-rundev.ir/api/song/download/11.mp3

**Comment by ryh** [comment]
`curl -I http://projectm.e-rundev.ir/api/song/download/11.mp3`
```
HTTP/1.1 200 OK
Date: Tue, 25 Apr 2017 13:36:34 GMT
Content-Type: text/html; charset=UTF-8
```
your server response wrong MIME type for .mp3 file. (was `text/html` should be `audio/mpeg`)
It's a server issue,  check with `nginx/apache MIME mp3`
REF:https://www.nginx.com/resources/wiki/start/topics/examples/full/

**Comment by muhammad-naderi** [comment]
thanks, actually changing server code to this snippet worked for me: 

```
        $file = storage_path() . '/upload/song/' . $filename;
        $mime_type = "audio/mpeg";
        $headers = array(
            'Accept-Ranges: 0-' . (filesize($file) -1) ,

            'Content-Length:'.filesize($file),
            'Content-Type:' . $mime_type,
            'Content-Disposition: inline; filename="'.$filename.'"'

        );
        $fileContents = File::get($file);
        return Response::make($fileContents, 200, $headers);
```

**Comment by tschob** [comment]
Thanks for helping out here @ryh

**Comment by muhammad-naderi** [comment]
sorry to reopen

but is there any header needed to feed the track.durationInSeconds() ?
as my own url time is 0, but I have samples who is working fine with same methods

**Comment by tschob** [comment]
Hi @muhammad-naderi, there shouldn't be something needed from the app side. I don't know how the server / files needs be provided in order to let the AVPlayer know of the track duration.

**Comment by tschob** [comment]
Issue is closed as it's not related to the library.
