### ISSUE TITLE
seek resets song

### ISSUE THREAD

**Issue by muhammad-naderi** [tschob/AudioPlayerManager#20]
hi, 

using following code, i'm not able to seek the song to my progress. it just restarts the song

        AudioPlayerManager.shared.seek(toProgress: songSlider.value)

songslider.value returns a correct float 

am i doing something wrong?

**Comment by tschob** [comment]
Hi @muhammad-naderi.

The seek call itself seems fine.
What is the maximum value of your Slider? It should be 1.0 as you call the percentage seek function.
If it is 1.0: Which URL are you playing?

**Comment by muhammad-naderi** [comment]
the maximum value is 1,
although as I asked here [https://github.com/tschob/AudioPlayerManager/issues/18#issuecomment-297647882] I'm not getting the total lenght of the song from your library (I'm getting it from my server, elseway) may this issue be the result of same problem ?

**Comment by tschob** [comment]
Relates to #18

**Comment by tschob** [comment]
Your url is played as live broadcast. As there is no information about the track duration it can't be possible to seek forward. You can easily test this behavior by opening the URL in Safari: No time slider is available.

**Comment by muhammad-naderi** [comment]
how about seeking back to a part which already has been played ?

**Comment by tschob** [comment]
Good idea, I may implement a function which seeks to time diference. Until when you can implement this by your own: 

```
guard let _currentTimeInSeconds = AudioPlayerManager.shared.currentTrack?.currentTimeInSeconds() else {
	return
}

var newTimeInSeconds = _currentTimeInSeconds - 10
if (newTimeInSeconds < 0) {
	newTimeInSeconds = 0
}
let time = CMTimeMake(Int64(newTimeInSeconds), 1)
AudioPlayerManager.shared.seek(toTime: time)

```

**Comment by muhammad-naderi** [comment]
this snippet did the complete job

```
        guard let _currentTimeInSeconds = AudioPlayerManager.shared.currentTrack?.currentTimeInSeconds() else {
            return
        }
        
        var newTimeInSeconds = songSlider.value * (songs[currentSongId].info?.getDurationInseconds())!
        if (newTimeInSeconds < 0) {
            newTimeInSeconds = 0
        }
        let time = CMTimeMake(Int64(newTimeInSeconds), 1)
        AudioPlayerManager.shared.seek(toTime: time)
```

where `songs[currentSongId].info?.getDurationInseconds())!` is giving me the total song duration from server

**Comment by tschob** [comment]
Close issue as question seems to answered.
