### ISSUE TITLE
Support background mode

### ISSUE THREAD

**Issue by muhammad-naderi** [tschob/AudioPlayerManager#22]
Hi, 

does this library support play in background ?

**Comment by tschob** [comment]
Yes, you just have to:
- enable the background mode in your project settings 
![bildschirmfoto 2017-04-30 um 15 24 07](https://cloud.githubusercontent.com/assets/3233717/25564718/78a04cfc-2db9-11e7-8506-e2ab58ebe22b.png)


- make sure `AudioPlayerManager.shared.setup()` is called before you play music.

**Comment by tschob** [comment]
Close issue as question seems to answered.
