### ISSUE TITLE
Play takes too long time in first time

### ISSUE THREAD

**Issue by pdmshrestha** [tschob/AudioPlayerManager#34]
Play doesn't work immediately on ios 10+. It works quite well below ios 10.

`guard let url = URL(string: (self?.mMediaItem.media!)!) else {
                    return
                }`

`let audioUrlTrack = AudioURLTrack(url: url)`
`AudioPlayerManager.shared.play(audioUrlTrack!)`

**Comment by tschob** [comment]
Duplicates #19

**Comment by pdmshrestha** [comment]
@tschob are you going to implement this feature?
