### ISSUE TITLE
Update for SWIFT 3 ?

### ISSUE THREAD

**Issue by Musgood** [tschob/AudioPlayerManager#6]
Hi! Very good job and i wonder is there any further update ?

**Comment by tschob** [comment]
Yes, I'll migrate it to SWIFT 3. It depends on my time but I think it should be done by this or next week.

**Comment by tschob** [comment]
🎉 AudioPlayerManager is now available in:
* Swift 2.2 as v 1.0.0 => https://github.com/tschob/AudioPlayerManager/releases/tag/1.0.0  
* Swift 2.3 as v 1.1.0 => https://github.com/tschob/AudioPlayerManager/releases/tag/1.1.0  
* Swift 3.0 as v 1.2.0 = > https://github.com/tschob/AudioPlayerManager/releases/tag/1.2.0

The further development will most likely take only place with Swift 3.0

**Comment by Musgood** [comment]
Thank you. Same thing, maintain other than 3.0 have no sense to me.
